setwd("R/exdata_data_household_power_consumption")
energy<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
energy<-na.omit(energy)
library(lubridate)
library(dplyr)
DateTime<-paste(energy$Date,energy$Time)
energy<-cbind(energy,DateTime)
energy$Time<-hms(energy$Time)
energy$Date<-dmy(energy$Date)
energy$DateTime<-dmy_hms(energy$DateTime)
energy<-energy %>% filter(Date >= as.Date("2007-02-01")) %>% filter(Date <= as.Date("2007-02-02"))
png(filename = "plot1.png", width = 480, height = 480, units = "px")
hist(energy$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
dev.off()